/**
 * visionEngine.js — Image Diagnosis Engine
 * ════════════════════════════════════════
 * 
 * Loads the custom-trained CNN (from Phase 3) via TensorFlow.js.
 * Preprocesses farmer image uploads (resize to 224x224, normalize).
 * Runs inference and returns the predicted class + softmax confidence.
 */

import * as tf from '@tensorflow/tfjs';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import jpeg from 'jpeg-js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Path to the TFJS model generated by convert_to_tfjs.py
const MODEL_DIR = path.join(__dirname, '../../model/output/tfjs_model');
const MODEL_URL = `file://${path.join(MODEL_DIR, 'model.json')}`;

// Classes exactly as defined in training (alphabetical order)
const CLASSES = [
  'bacterial_rot',
  'black_rot',
  'downy_mildew',
  'esca',
  'healthy',
  'leaf_blight',
  'powdery_mildew'
];

let cnnModel = null;
let isReady = false;

function cleanLayerConfig(config) {
  if (!config || typeof config !== 'object') return config;
  if (Array.isArray(config)) return config.map(cleanLayerConfig);

  const cleaned = {};
  for (let [k, v] of Object.entries(config)) {
    if (k === 'module' || k === 'registered_name') continue;
    if (k.includes('regularizer') || k.includes('Regularizer')) v = null;
    if (k === 'batch_input_shape') k = 'batchInputShape';
    if (k === 'data_format') k = 'dataFormat';
    if (k === 'kernel_size') k = 'kernelSize';
    if (k === 'dilation_rate') k = 'dilationRate';
    if (k === 'use_bias') k = 'useBias';
    if (k === 'pool_size') k = 'poolSize';
    if (k === 'axis' && Array.isArray(v)) v = v[0];
    cleaned[k] = cleanLayerConfig(v);
  }
  return cleaned;
}

function cleanKerasTopology(topology) {
  const cleaned = JSON.parse(JSON.stringify(topology));
  if (cleaned.model_config && cleaned.model_config.config && cleaned.model_config.config.layers) {
    cleaned.model_config.config.layers = cleaned.model_config.config.layers.map(layer => {
      if (layer.config) layer.config = cleanLayerConfig(layer.config);
      return layer;
    });
  }
  return cleaned;
}

/**
 * Custom TFJS IOHandler to load model.json and .bin weight shards from local disk in Node.js
 */
function createLocalModelLoader(modelJsonPath) {
  return {
    load: async () => {
      const modelJsonDir = path.dirname(modelJsonPath);
      const rawJson = JSON.parse(fs.readFileSync(modelJsonPath, 'utf8'));

      const modelTopology = cleanKerasTopology(rawJson.modelTopology);
      const weightsManifest = rawJson.weightsManifest;

      const weightSpecs = [];
      const weightBuffers = [];

      for (const group of weightsManifest) {
        weightSpecs.push(...group.weights);
        for (const filename of group.paths) {
          const weightPath = path.join(modelJsonDir, filename);
          const buf = fs.readFileSync(weightPath);
          weightBuffers.push(buf);
        }
      }

      const combinedBuffer = Buffer.concat(weightBuffers);
      const weightData = combinedBuffer.buffer.slice(
        combinedBuffer.byteOffset,
        combinedBuffer.byteOffset + combinedBuffer.byteLength
      );

      return {
        modelTopology,
        weightSpecs,
        weightData
      };
    }
  };
}

/**
 * Initialize the CNN model on server startup.
 */
export async function initVisionEngine() {
  try {
    const modelJsonPath = path.join(MODEL_DIR, 'model.json');
    if (!fs.existsSync(modelJsonPath)) {
      console.warn('⚠️ CNN model.json not found. Did you run the training script? Vision Engine running in mock mode.');
      return;
    }

    console.log('⏳ Loading custom CNN Vision Model from disk...');
    cnnModel = await tf.loadLayersModel(createLocalModelLoader(modelJsonPath));
    isReady = true;
    console.log('✅ CNN Vision Model loaded successfully.');
    
    // Warm up the model (optional, speeds up first inference)
    cnnModel.predict(tf.zeros([1, 224, 224, 3])).dispose();
  } catch (error) {
    console.error('❌ Failed to load CNN model:', error);
  }
}

/**
 * Process an uploaded image and predict the disease.
 * 
 * @param {string} imagePath - Absolute path to the uploaded image file
 * @returns {Object} { prediction, confidence }
 */
export async function analyzeImage(imagePath) {
  if (!fs.existsSync(imagePath)) {
    throw new Error('Image file not found');
  }

  // If the model hasn't been trained/loaded yet, return a mock response
  // so the rest of the RAG pipeline can still be tested.
  if (!isReady || !cnnModel) {
    console.warn('⚠️ Vision Engine in mock mode (model not loaded). Returning simulated diagnosis.');
    return {
      prediction: 'powdery_mildew',
      confidence: 0.88,
      isMock: true
    };
  }

  try {
    // 1. Read image file into a buffer
    const imageBuffer = fs.readFileSync(imagePath);
    
    // 2. Decode image and preprocess
    // We use jpeg-js to decode the image natively in JS to avoid tfjs-node build issues.
    const rawImageData = jpeg.decode(imageBuffer, { useTArray: true }); // width, height, data (Uint8Array RGBA)
    
    // Convert RGBA to RGB and normalize to [0, 1] exactly as the model was trained
    const numPixels = rawImageData.width * rawImageData.height;
    const rgbData = new Float32Array(numPixels * 3);
    for (let i = 0; i < numPixels; i++) {
      rgbData[i * 3] = rawImageData.data[i * 4] / 255.0;         // R
      rgbData[i * 3 + 1] = rawImageData.data[i * 4 + 1] / 255.0; // G
      rgbData[i * 3 + 2] = rawImageData.data[i * 4 + 2] / 255.0; // B
    }

    const tensor = tf.tensor3d(rgbData, [rawImageData.height, rawImageData.width, 3])
      .resizeBilinear([224, 224])
      .expandDims(0);

    // 3. Run Inference
    const predictions = await cnnModel.predict(tensor).data();
    
    // 4. Find the highest probability class
    let maxIdx = 0;
    let maxConfidence = predictions[0];
    for (let i = 1; i < predictions.length; i++) {
      if (predictions[i] > maxConfidence) {
        maxConfidence = predictions[i];
        maxIdx = i;
      }
    }

    tensor.dispose(); // Free memory

    // Convert internal class name to readable format
    const readablePrediction = formatClassName(CLASSES[maxIdx]);

    return {
      prediction: readablePrediction,
      confidence: maxConfidence,
      isMock: false
    };

  } catch (error) {
    console.error('❌ Error during image analysis:', error);
    throw new Error('Image analysis failed');
  }
}

function formatClassName(className) {
  return className.split('_').map(word => 
    word.charAt(0).toUpperCase() + word.slice(1)
  ).join(' ');
}
